-- Panorama PMO — Seed verisi
-- Excel masterlarından üretildi: KeyAccount_Projeler.xlsx (26) + VolumeHub_Projeler.xlsx (59)

-- Hub'lar (Stokbar yapı hazır, veri sonra)
insert into hubs (ad, renk, sira) values
  ('Key Account', '#38BDF8', 1),
  ('Volume', '#34D399', 2),
  ('Stokbar', '#FB923C', 3);

-- Ürünler
insert into products (ad) values ('Enroute'), ('Quest'), ('Calldesk'), ('Stokbar');

-- Unvanlar
insert into job_titles (ad, sira) values
  ('Proje Yöneticisi', 1), ('Uygulama Danışmanı', 2), ('Yazılım Destek', 3);

-- İş tipleri (5 sabit)
insert into work_types (ad, sira) values
  ('Analiz', 1), ('Geliştirme/Uyarlama', 2), ('Test', 3), ('Destek', 4), ('Toplantı/Koordinasyon', 5);

-- Beklemede nedenleri (3 sabit)
insert into waiting_reasons (ad, sira) values
  ('Müşteri bekleniyor', 1), ('İç bağımlılık', 2), ('Üçüncü taraf bekleniyor', 3);

-- ============ Key Account hub (20 müşteri, 26 proje) ============

insert into customers (hub_id, ad) values
  ((select id from hubs where ad = 'Key Account'), 'BMC'),
  ((select id from hubs where ad = 'Key Account'), 'BRISA BRIDGESTONE'),
  ((select id from hubs where ad = 'Key Account'), 'BROWN FORMAN'),
  ((select id from hubs where ad = 'Key Account'), 'DANONE'),
  ((select id from hubs where ad = 'Key Account'), 'DOĞUŞ ÇAY'),
  ((select id from hubs where ad = 'Key Account'), 'DÜZEY TÜKETİM'),
  ((select id from hubs where ad = 'Key Account'), 'ECZACIBASI'),
  ((select id from hubs where ad = 'Key Account'), 'HARİBO'),
  ((select id from hubs where ad = 'Key Account'), 'HAYAT KİMYA'),
  ((select id from hubs where ad = 'Key Account'), 'JTI'),
  ((select id from hubs where ad = 'Key Account'), 'JTI IRAN'),
  ((select id from hubs where ad = 'Key Account'), 'KENT GIDA'),
  ((select id from hubs where ad = 'Key Account'), 'MEY İÇKİ'),
  ((select id from hubs where ad = 'Key Account'), 'NESTLE'),
  ((select id from hubs where ad = 'Key Account'), 'PERNOD RİCARD'),
  ((select id from hubs where ad = 'Key Account'), 'SEN PİLİÇ'),
  ((select id from hubs where ad = 'Key Account'), 'SÖLEN'),
  ((select id from hubs where ad = 'Key Account'), 'SÖLEN IRAK'),
  ((select id from hubs where ad = 'Key Account'), 'TOGG'),
  ((select id from hubs where ad = 'Key Account'), 'ULUDAĞ İÇECEK');

insert into projects (customer_id, ad) values
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BMC'), 'BMC'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BRISA BRIDGESTONE'), 'BRISA BRIDGESTONE'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BROWN FORMAN'), 'BROWN FORMAN'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DANONE'), 'DANONE TİKVESLİ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DANONE'), 'DANONE WATERS'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DOĞUŞ ÇAY'), 'DOĞUŞ ÇAY'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DÜZEY TÜKETİM'), 'DÜZEY TÜKETİM'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ECZACIBASI'), 'ECZACIBASI GİRİŞİM'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ECZACIBASI'), 'ECZACIBASI İNTEMA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ECZACIBASI'), 'ECZACIBASI PROFESYONEL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'HARİBO'), 'HARİBO'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'HAYAT KİMYA'), 'HAYAT KİMYA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'JTI'), 'JTI'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'JTI IRAN'), 'JTI IRAN'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'KENT GIDA'), 'KENT GIDA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'MEY İÇKİ'), 'MEY İÇKİ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE'), 'NESTLE PROFESİONAL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE'), 'NESTLE RETAİL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE'), 'NESTLE ROM'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE'), 'NESTLE WATERS'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'PERNOD RİCARD'), 'PERNOD RİCARD'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'SEN PİLİÇ'), 'SEN PİLİÇ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'SÖLEN'), 'SÖLEN'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'SÖLEN IRAK'), 'SÖLEN IRAK'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'TOGG'), 'TOGG'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ULUDAĞ İÇECEK'), 'ULUDAĞ İÇECEK');

insert into project_products (project_id, product_id) values
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BMC' and p.ad = 'BMC'), (select id from products where ad = 'Calldesk')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BMC' and p.ad = 'BMC'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BMC' and p.ad = 'BMC'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BRISA BRIDGESTONE' and p.ad = 'BRISA BRIDGESTONE'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BROWN FORMAN' and p.ad = 'BROWN FORMAN'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'BROWN FORMAN' and p.ad = 'BROWN FORMAN'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DANONE' and p.ad = 'DANONE TİKVESLİ'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DANONE' and p.ad = 'DANONE WATERS'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DOĞUŞ ÇAY' and p.ad = 'DOĞUŞ ÇAY'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DOĞUŞ ÇAY' and p.ad = 'DOĞUŞ ÇAY'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DOĞUŞ ÇAY' and p.ad = 'DOĞUŞ ÇAY'), (select id from products where ad = 'Stokbar')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'DÜZEY TÜKETİM' and p.ad = 'DÜZEY TÜKETİM'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ECZACIBASI' and p.ad = 'ECZACIBASI GİRİŞİM'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ECZACIBASI' and p.ad = 'ECZACIBASI İNTEMA'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ECZACIBASI' and p.ad = 'ECZACIBASI PROFESYONEL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'HARİBO' and p.ad = 'HARİBO'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'HAYAT KİMYA' and p.ad = 'HAYAT KİMYA'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'JTI' and p.ad = 'JTI'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'JTI' and p.ad = 'JTI'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'JTI IRAN' and p.ad = 'JTI IRAN'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'JTI IRAN' and p.ad = 'JTI IRAN'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'KENT GIDA' and p.ad = 'KENT GIDA'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'KENT GIDA' and p.ad = 'KENT GIDA'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'KENT GIDA' and p.ad = 'KENT GIDA'), (select id from products where ad = 'Stokbar')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'MEY İÇKİ' and p.ad = 'MEY İÇKİ'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'MEY İÇKİ' and p.ad = 'MEY İÇKİ'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE' and p.ad = 'NESTLE PROFESİONAL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE' and p.ad = 'NESTLE PROFESİONAL'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE' and p.ad = 'NESTLE RETAİL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE' and p.ad = 'NESTLE RETAİL'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE' and p.ad = 'NESTLE ROM'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE' and p.ad = 'NESTLE ROM'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE' and p.ad = 'NESTLE WATERS'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'NESTLE' and p.ad = 'NESTLE WATERS'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'PERNOD RİCARD' and p.ad = 'PERNOD RİCARD'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'SEN PİLİÇ' and p.ad = 'SEN PİLİÇ'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'SÖLEN' and p.ad = 'SÖLEN'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'SÖLEN IRAK' and p.ad = 'SÖLEN IRAK'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'TOGG' and p.ad = 'TOGG'), (select id from products where ad = 'Calldesk')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ULUDAĞ İÇECEK' and p.ad = 'ULUDAĞ İÇECEK'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Key Account' and c.ad = 'ULUDAĞ İÇECEK' and p.ad = 'ULUDAĞ İÇECEK'), (select id from products where ad = 'Quest'));

-- ============ Volume hub (53 müşteri, 59 proje) ============

insert into customers (hub_id, ad) values
  ((select id from hubs where ad = 'Volume'), 'ALPEDO'),
  ((select id from hubs where ad = 'Volume'), 'ALTIPARMAK'),
  ((select id from hubs where ad = 'Volume'), 'ANADOLU MOTOR'),
  ((select id from hubs where ad = 'Volume'), 'ARÇELİK / BEKO GLOBAL / HİTACHİ'),
  ((select id from hubs where ad = 'Volume'), 'AYDEM'),
  ((select id from hubs where ad = 'Volume'), 'BELGİN-BELKİM'),
  ((select id from hubs where ad = 'Volume'), 'BEYLERBEYİ'),
  ((select id from hubs where ad = 'Volume'), 'BRİSA'),
  ((select id from hubs where ad = 'Volume'), 'BUNGE'),
  ((select id from hubs where ad = 'Volume'), 'BURDA BEBEK'),
  ((select id from hubs where ad = 'Volume'), 'DARDANEL'),
  ((select id from hubs where ad = 'Volume'), 'DEVA İÇECEK'),
  ((select id from hubs where ad = 'Volume'), 'DOĞADAN'),
  ((select id from hubs where ad = 'Volume'), 'DOĞANAY'),
  ((select id from hubs where ad = 'Volume'), 'EFES'),
  ((select id from hubs where ad = 'Volume'), 'EFES PİLSEN'),
  ((select id from hubs where ad = 'Volume'), 'ERUSLU'),
  ((select id from hubs where ad = 'Volume'), 'EVYAP'),
  ((select id from hubs where ad = 'Volume'), 'FHP VİLEDA'),
  ((select id from hubs where ad = 'Volume'), 'GSK'),
  ((select id from hubs where ad = 'Volume'), 'HENKEL'),
  ((select id from hubs where ad = 'Volume'), 'HOBBY'),
  ((select id from hubs where ad = 'Volume'), 'JDE'),
  ((select id from hubs where ad = 'Volume'), 'KEBİR SÜT'),
  ((select id from hubs where ad = 'Volume'), 'KOROPLAST'),
  ((select id from hubs where ad = 'Volume'), 'KÜRESEL TEDARİK'),
  ((select id from hubs where ad = 'Volume'), 'LA LORRAINE'),
  ((select id from hubs where ad = 'Volume'), 'LEVENT KİMYA'),
  ((select id from hubs where ad = 'Volume'), 'LOREAL'),
  ((select id from hubs where ad = 'Volume'), 'MARS GIDA'),
  ((select id from hubs where ad = 'Volume'), 'MARSHALL'),
  ((select id from hubs where ad = 'Volume'), 'MONDELEZ'),
  ((select id from hubs where ad = 'Volume'), 'NETLOG KÜRESEL'),
  ((select id from hubs where ad = 'Volume'), 'NUROL MAKİNA'),
  ((select id from hubs where ad = 'Volume'), 'NİVEA'),
  ((select id from hubs where ad = 'Volume'), 'OPET ENDÜSTRİYEL'),
  ((select id from hubs where ad = 'Volume'), 'PAŞABAHÇE'),
  ((select id from hubs where ad = 'Volume'), 'PERRIGO'),
  ((select id from hubs where ad = 'Volume'), 'RECKITT BENCKISER'),
  ((select id from hubs where ad = 'Volume'), 'REDBULL'),
  ((select id from hubs where ad = 'Volume'), 'ROYAL CANIN'),
  ((select id from hubs where ad = 'Volume'), 'SATEM GRUP'),
  ((select id from hubs where ad = 'Volume'), 'SCHWARZKOPF'),
  ((select id from hubs where ad = 'Volume'), 'SÜTAŞ'),
  ((select id from hubs where ad = 'Volume'), 'TADIM'),
  ((select id from hubs where ad = 'Volume'), 'TURKUAZ'),
  ((select id from hubs where ad = 'Volume'), 'TÜRKTAB'),
  ((select id from hubs where ad = 'Volume'), 'VODAFONE'),
  ((select id from hubs where ad = 'Volume'), 'VODAFONE KIBRIS'),
  ((select id from hubs where ad = 'Volume'), 'ÇAYKUR'),
  ((select id from hubs where ad = 'Volume'), 'ÖZGORKEY'),
  ((select id from hubs where ad = 'Volume'), 'ÜLKER / PLADİS'),
  ((select id from hubs where ad = 'Volume'), 'İMPERİAL TOBACCO');

insert into projects (customer_id, ad) values
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ALPEDO'), 'ALPEDO'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ALTIPARMAK'), 'ALTIPARMAK'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ANADOLU MOTOR'), 'ANADOLU MOTOR'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ARÇELİK / BEKO GLOBAL / HİTACHİ'), 'ARÇELİK / BEKO GLOBAL / HİTACHİ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'AYDEM'), 'AYDEM A.D.M'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'AYDEM'), 'AYDEM GDZ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'AYDEM'), 'AYDEM PERAKENDE SATIŞ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'AYDEM'), 'AYDEM YENİLENEBİLİR ENERJİ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BELGİN-BELKİM'), 'BELGİN-BELKİM'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BEYLERBEYİ'), 'BEYLERBEYİ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BRİSA'), 'BRİSA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BUNGE'), 'BUNGE'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BURDA BEBEK'), 'BURDA BEBEK'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'DARDANEL'), 'DARDANEL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'DEVA İÇECEK'), 'DEVA İÇECEK'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'DOĞADAN'), 'DOĞADAN'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'DOĞANAY'), 'DOĞANAY'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EFES'), 'EFES GÜRCİSTAN'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EFES'), 'EFES KAZAKİSTAN'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EFES'), 'EFES MOLDOVA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EFES PİLSEN'), 'EFES PİLSEN'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ERUSLU'), 'ERUSLU'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EVYAP'), 'EVYAP'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'FHP VİLEDA'), 'FHP VİLEDA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'GSK'), 'GSK'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'HENKEL'), 'HENKEL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'HOBBY'), 'HOBBY'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'JDE'), 'JDE'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'KEBİR SÜT'), 'KEBİR SÜT'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'KOROPLAST'), 'KOROPLAST'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'KÜRESEL TEDARİK'), 'KÜRESEL TEDARİK (ANELE)'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'LA LORRAINE'), 'LA LORRAINE'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'LEVENT KİMYA'), 'LEVENT KİMYA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'LOREAL'), 'LOREAL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'MARS GIDA'), 'MARS GIDA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'MARSHALL'), 'MARSHALL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'MONDELEZ'), 'MONDELEZ (FA SATIŞ YÖNETİCİLERİ)'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'NETLOG KÜRESEL'), 'NETLOG KÜRESEL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'NUROL MAKİNA'), 'NUROL MAKİNA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'NİVEA'), 'NİVEA'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'OPET ENDÜSTRİYEL'), 'OPET ENDÜSTRİYEL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'PAŞABAHÇE'), 'PAŞABAHÇE'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'PERRIGO'), 'PERRIGO'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'RECKITT BENCKISER'), 'RECKITT BENCKISER'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'REDBULL'), 'REDBULL'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ROYAL CANIN'), 'ROYAL CANIN'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SATEM GRUP'), 'SATEM GRUP'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SCHWARZKOPF'), 'SCHWARZKOPF'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SÜTAŞ'), 'SÜTAŞ ESY'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SÜTAŞ'), 'SÜTAŞ MONO'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'TADIM'), 'TADIM'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'TURKUAZ'), 'TURKUAZ'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'TÜRKTAB'), 'TÜRKTAB'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'VODAFONE'), 'VODAFONE'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'VODAFONE KIBRIS'), 'VODAFONE KIBRIS'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ÇAYKUR'), 'ÇAYKUR'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ÖZGORKEY'), 'ÖZGORKEY'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ÜLKER / PLADİS'), 'ÜLKER / PLADİS'),
  ((select c.id from customers c join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'İMPERİAL TOBACCO'), 'İMPERİAL TOBACCO');

insert into project_products (project_id, product_id) values
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ALPEDO' and p.ad = 'ALPEDO'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ALTIPARMAK' and p.ad = 'ALTIPARMAK'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ANADOLU MOTOR' and p.ad = 'ANADOLU MOTOR'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ARÇELİK / BEKO GLOBAL / HİTACHİ' and p.ad = 'ARÇELİK / BEKO GLOBAL / HİTACHİ'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'AYDEM' and p.ad = 'AYDEM A.D.M'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'AYDEM' and p.ad = 'AYDEM GDZ'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'AYDEM' and p.ad = 'AYDEM PERAKENDE SATIŞ'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'AYDEM' and p.ad = 'AYDEM YENİLENEBİLİR ENERJİ'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BELGİN-BELKİM' and p.ad = 'BELGİN-BELKİM'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BEYLERBEYİ' and p.ad = 'BEYLERBEYİ'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BRİSA' and p.ad = 'BRİSA'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BUNGE' and p.ad = 'BUNGE'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BURDA BEBEK' and p.ad = 'BURDA BEBEK'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'BURDA BEBEK' and p.ad = 'BURDA BEBEK'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'DARDANEL' and p.ad = 'DARDANEL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'DEVA İÇECEK' and p.ad = 'DEVA İÇECEK'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'DOĞADAN' and p.ad = 'DOĞADAN'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'DOĞANAY' and p.ad = 'DOĞANAY'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EFES' and p.ad = 'EFES GÜRCİSTAN'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EFES' and p.ad = 'EFES KAZAKİSTAN'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EFES' and p.ad = 'EFES MOLDOVA'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EFES PİLSEN' and p.ad = 'EFES PİLSEN'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ERUSLU' and p.ad = 'ERUSLU'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EVYAP' and p.ad = 'EVYAP'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'EVYAP' and p.ad = 'EVYAP'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'FHP VİLEDA' and p.ad = 'FHP VİLEDA'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'GSK' and p.ad = 'GSK'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'HENKEL' and p.ad = 'HENKEL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'HOBBY' and p.ad = 'HOBBY'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'JDE' and p.ad = 'JDE'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'KEBİR SÜT' and p.ad = 'KEBİR SÜT'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'KOROPLAST' and p.ad = 'KOROPLAST'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'KÜRESEL TEDARİK' and p.ad = 'KÜRESEL TEDARİK (ANELE)'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'LA LORRAINE' and p.ad = 'LA LORRAINE'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'LEVENT KİMYA' and p.ad = 'LEVENT KİMYA'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'LOREAL' and p.ad = 'LOREAL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'LOREAL' and p.ad = 'LOREAL'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'MARS GIDA' and p.ad = 'MARS GIDA'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'MARS GIDA' and p.ad = 'MARS GIDA'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'MARSHALL' and p.ad = 'MARSHALL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'MONDELEZ' and p.ad = 'MONDELEZ (FA SATIŞ YÖNETİCİLERİ)'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'NETLOG KÜRESEL' and p.ad = 'NETLOG KÜRESEL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'NUROL MAKİNA' and p.ad = 'NUROL MAKİNA'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'NİVEA' and p.ad = 'NİVEA'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'OPET ENDÜSTRİYEL' and p.ad = 'OPET ENDÜSTRİYEL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'PAŞABAHÇE' and p.ad = 'PAŞABAHÇE'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'PERRIGO' and p.ad = 'PERRIGO'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'RECKITT BENCKISER' and p.ad = 'RECKITT BENCKISER'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'REDBULL' and p.ad = 'REDBULL'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ROYAL CANIN' and p.ad = 'ROYAL CANIN'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ROYAL CANIN' and p.ad = 'ROYAL CANIN'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SATEM GRUP' and p.ad = 'SATEM GRUP'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SATEM GRUP' and p.ad = 'SATEM GRUP'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SCHWARZKOPF' and p.ad = 'SCHWARZKOPF'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SÜTAŞ' and p.ad = 'SÜTAŞ ESY'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SÜTAŞ' and p.ad = 'SÜTAŞ ESY'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'SÜTAŞ' and p.ad = 'SÜTAŞ MONO'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'TADIM' and p.ad = 'TADIM'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'TADIM' and p.ad = 'TADIM'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'TURKUAZ' and p.ad = 'TURKUAZ'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'TÜRKTAB' and p.ad = 'TÜRKTAB'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'VODAFONE' and p.ad = 'VODAFONE'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'VODAFONE KIBRIS' and p.ad = 'VODAFONE KIBRIS'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ÇAYKUR' and p.ad = 'ÇAYKUR'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ÇAYKUR' and p.ad = 'ÇAYKUR'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ÖZGORKEY' and p.ad = 'ÖZGORKEY'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'ÜLKER / PLADİS' and p.ad = 'ÜLKER / PLADİS'), (select id from products where ad = 'Quest')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'İMPERİAL TOBACCO' and p.ad = 'İMPERİAL TOBACCO'), (select id from products where ad = 'Enroute')),
  ((select p.id from projects p join customers c on c.id = p.customer_id join hubs h on h.id = c.hub_id where h.ad = 'Volume' and c.ad = 'İMPERİAL TOBACCO' and p.ad = 'İMPERİAL TOBACCO'), (select id from products where ad = 'Quest'));
